In [2]:

import pathlib
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
print(tf.__version__)


2.5.0


In [12]:
t = tf.constant([[1.,2.,3.],[4.,5.,6.]])
# index
print(t)
print(t[:,1:])
print(t[...,1])

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)
tf.Tensor([2. 5.], shape=(2,), dtype=float32)


In [14]:
# ops
print(t+10)
print(tf.square(t))
# @ tf 矩阵乘法
print(t @ tf.transpose(t))

tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)


In [17]:
# numpy conversion
print(t.numpy())
print(np.square(t))
np_t = np.array([[1.,2.,3.],[4.,5.,6.]])
print(tf.constant(np_t))

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)


In [18]:
# Scalars 零维常数
t = tf.constant(3.14)
print(t)

tf.Tensor(3.14, shape=(), dtype=float32)


In [22]:
# string
t = tf.constant("cafe")
print(t)
print(tf.strings.length(t))
print(tf.strings.length(t,unit='UTF8_CHAR'))
print(tf.strings.unicode_decode(t,'UTF8'))

tf.Tensor(b'cafe', shape=(), dtype=string)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([ 99  97 102 101], shape=(4,), dtype=int32)


In [23]:
# string array
t = tf.constant(["cafe","coffee","咖啡"])
print(t)
print(tf.strings.length(t))
print(tf.strings.length(t,unit='UTF8_CHAR'))
print(tf.strings.unicode_decode(t,'UTF8'))

tf.Tensor([b'cafe' b'coffee' b'\xe5\x92\x96\xe5\x95\xa1'], shape=(3,), dtype=string)
tf.Tensor([4 6 6], shape=(3,), dtype=int32)
tf.Tensor([4 6 2], shape=(3,), dtype=int32)
<tf.RaggedTensor [[99, 97, 102, 101], [99, 111, 102, 102, 101, 101], [21654, 21857]]>


In [26]:
#ragged tensor
r = tf.ragged.constant([[11,12],[21,22,23],[],[41]])
# index op
print(r)
print(r[1])
print(r[1:2])

<tf.RaggedTensor [[11, 12], [21, 22, 23], [], [41]]>
tf.Tensor([21 22 23], shape=(3,), dtype=int32)
<tf.RaggedTensor [[21, 22, 23]]>


In [29]:
# ops on ragged tensor
r2 = tf.ragged.constant([[51,52],[],[],[71]])
print(tf.concat([r,r2],axis=0))
print(tf.concat([r,r2],axis=1))

<tf.RaggedTensor [[11, 12], [21, 22, 23], [], [41], [51, 52], [], [], [71]]>
<tf.RaggedTensor [[11, 12, 51, 52], [21, 22, 23], [], [41, 71]]>


In [30]:
# 空缺位置0补全
r2.to_tensor()

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[51, 52],
       [ 0,  0],
       [ 0,  0],
       [71,  0]], dtype=int32)>

In [32]:
# sparse tensor
s = tf.SparseTensor(indices=[[0,1],[1,0],[2,3]],values=[1.,2.,3.],
                   dense_shape=[3,4])
print(s)
print(tf.sparse.to_dense(s))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0. 1. 0. 0.]
 [2. 0. 0. 0.]
 [0. 0. 0. 3.]], shape=(3, 4), dtype=float32)


In [44]:
# ops on sparse tensors
s2 = s * 2.0
print(s2)
try:
    s3 = s + 1
except TypeError as ex:
    print(ex)
    
s4 = tf.constant(np.array(np.arange(8).reshape(4,-1),dtype='float32'))
print(tf.sparse.sparse_dense_matmul(s,s4))
print(tf.sparse.to_dense(s) @ s4)

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
unsupported operand type(s) for +: 'SparseTensor' and 'int'
tf.Tensor(
[[ 2.  3.]
 [ 0.  2.]
 [18. 21.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ 2.  3.]
 [ 0.  2.]
 [18. 21.]], shape=(3, 2), dtype=float32)


In [47]:
# sparse tensor
s5 = tf.SparseTensor(indices=[[0,2],[0,1],[2,3]],values=[1.,2.,3.],
                   dense_shape=[3,4])
print(s5)
s6 = tf.sparse.reorder(s5)
print(tf.sparse.to_dense(s6))

SparseTensor(indices=tf.Tensor(
[[0 2]
 [0 1]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0. 2. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 3.]], shape=(3, 4), dtype=float32)


In [49]:
# variables
v = tf.Variable([[1.,2.,3.],[4.,5.,6.]])
print(v)
print(v.value)
print(v.numpy)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>
<bound method BaseResourceVariable.value of <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>>
<bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>>


In [50]:
# assign value
v.assign(2*v)
print(v.numpy())
v[0,1].assign(42)
print(v.numpy())
v[1].assign([7.,8.,99.])
print(v.numpy())

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[ 2. 42.  6.]
 [ 8. 10. 12.]]
[[ 2. 42.  6.]
 [ 7.  8. 99.]]


In [51]:
try:
    v[1] = [1,2,3]
except TypeError as ex:
    print(ex)

'ResourceVariable' object does not support item assignment
